version: '3.1'

services:
  pong:
    build: .
    ports:
      - 8000:8000
    cap_drop:
      - "ALL"
    read_only: true
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev-environment-pass